support more types
gimbles/Rakh pull request #5
Opened 2022-01-24 15:49 UTC by knassar702

hello @Yush08 thanks for this crate, I added new types like integer, float, bool and I'm working on the array and hashmap types 

here's the new format
```
name:"string between \"\" "
bool:true
number:55
float:1.4
```

best regards

2022-02-15 03:47 UTC, Yush08 commented
Hello! Sorry for the late reply, I will definitely take a look at this PR and merge it soon!

Somehow the notification didn't pop up, I'll take a peek right now :P

2022-02-15 03:50 UTC, Yush08 requested changes
Thanks for the PR! Really appreciate it -- can you check on these requests please?

2022-02-15 03:50 UTC, Yush08 commented on src/lib.rs
> -        let config =
I'd appreciate it if you could not remove these tests :)

2022-02-15 03:50 UTC, Yush08 commented on src/lib.rs
> +        assert_eq!(config.get("test").unwrap(), &Types::Boolean(true));
Could you add a few more tests please? Especially with your object type.

2022-02-23 15:32 UTC, knassar702 commented on src/lib.rs
> -        let config =
sure :+1:

2022-02-23 16:37 UTC, gimbles approved these changes

2022-02-23 16:38 UTC, gimbles commented
Appreciate the help on this, I'll test it out locally and merge in a few minutes

2022-02-23 16:40 UTC, merged